"""customer account activation schema

Revision ID: 20260902_0001
Revises:
Create Date: 2026-09-02 02:50:01.052884
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260902_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "viewer",
                "operator",
                "administrator",
                name="admin_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="viewer",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_admin_users_admin_email_normalized")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_index(op.f("ix_admin_users_role"), "admin_users", ["role"], unique=False)
    op.create_table(
        "packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GHS", nullable=False),
        sa.Column("duration_seconds", sa.BigInteger(), nullable=False),
        sa.Column("data_limit_bytes", sa.BigInteger(), nullable=True),
        sa.Column("device_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_packages_package_amount_non_negative")),
        sa.CheckConstraint(
            "char_length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_packages_package_currency_iso_code"),
        ),
        sa.CheckConstraint(
            "data_limit_bytes IS NULL OR data_limit_bytes > 0",
            name=op.f("ck_packages_package_data_limit_positive"),
        ),
        sa.CheckConstraint(
            "device_limit IS NULL OR device_limit > 0",
            name=op.f("ck_packages_package_device_limit_positive"),
        ),
        sa.CheckConstraint(
            "duration_seconds > 0", name=op.f("ck_packages_package_duration_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
    )
    op.create_index(op.f("ix_packages_code"), "packages", ["code"], unique=True)
    op.create_table(
        "routers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("vpn_host", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "unknown",
                "online",
                "offline",
                "maintenance",
                name="router_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(id) > 0", name=op.f("ck_routers_router_id_not_blank")),
        sa.CheckConstraint("char_length(name) > 0", name=op.f("ck_routers_router_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routers")),
        sa.UniqueConstraint("vpn_host", name=op.f("uq_routers_vpn_host")),
    )
    op.create_index(op.f("ix_routers_status"), "routers", ["status"], unique=False)
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_sessions_admin_user_id_admin_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_user_id"), "admin_sessions", ["admin_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_admin_sessions_expires_at"), "admin_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_admin_sessions_token_hash"), "admin_sessions", ["token_hash"], unique=True
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "account_status",
            sa.Enum(
                "inactive",
                "active",
                "suspended",
                "closed",
                name="account_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="inactive",
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mikrotik_user_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(username) >= 3", name=op.f("ck_customers_customer_username_min_length")
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_customers_customer_email_normalized")
        ),
        sa.CheckConstraint(
            "username = lower(username)", name=op.f("ck_customers_customer_username_normalized")
        ),
        sa.ForeignKeyConstraint(
            ["router_id"],
            ["routers.id"],
            name=op.f("fk_customers_router_id_routers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        op.f("ix_customers_account_status"), "customers", ["account_status"], unique=False
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=True)
    op.create_index(op.f("ix_customers_router_id"), "customers", ["router_id"], unique=False)
    op.create_index(op.f("ix_customers_username"), "customers", ["username"], unique=True)
    op.create_table(
        "router_package_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("mikrotik_profile", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(mikrotik_profile) > 0",
            name=op.f("ck_router_package_profiles_mikrotik_profile_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_router_package_profiles_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["router_id"],
            ["routers.id"],
            name=op.f("fk_router_package_profiles_router_id_routers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_router_package_profiles")),
        sa.UniqueConstraint("router_id", "mikrotik_profile", name="uq_router_mikrotik_profile"),
        sa.UniqueConstraint("router_id", "package_id", name="uq_router_package_profile"),
    )
    op.create_index(
        op.f("ix_router_package_profiles_package_id"),
        "router_package_profiles",
        ["package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_router_package_profiles_router_id"),
        "router_package_profiles",
        ["router_id"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "customer",
                "admin",
                "system",
                name="audit_actor_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("admin_user_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_audit_logs_admin_user_id_admin_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_audit_logs_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_type"), "audit_logs", ["actor_type"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_admin_user_id"), "audit_logs", ["admin_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_customer_id"), "audit_logs", ["customer_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "customer_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_sessions_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_sessions")),
    )
    op.create_index(
        op.f("ix_customer_sessions_customer_id"), "customer_sessions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_expires_at"), "customer_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_token_hash"), "customer_sessions", ["token_hash"], unique=True
    )
    op.create_table(
        "email_otp_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "registration",
                "username_recovery",
                "pin_reset",
                name="otp_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_email_otp_challenges_otp_attempt_count_non_negative"),
        ),
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_email_otp_challenges_otp_email_normalized")
        ),
        sa.CheckConstraint(
            "max_attempts > 0", name=op.f("ck_email_otp_challenges_otp_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_email_otp_challenges_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_otp_challenges")),
    )
    op.create_index(
        op.f("ix_email_otp_challenges_created_at"),
        "email_otp_challenges",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_otp_challenges_customer_id"),
        "email_otp_challenges",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_otp_challenges_email"), "email_otp_challenges", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_email_otp_challenges_expires_at"),
        "email_otp_challenges",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_otp_challenges_purpose"), "email_otp_challenges", ["purpose"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=False),
        sa.Column("paystack_reference", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GHS", nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum(
                "pending",
                "success",
                "failed",
                name="payment_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("provider_status", sa.String(length=80), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_transactions_transaction_amount_non_negative")
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3 AND currency = upper(currency)",
            name=op.f("ck_transactions_transaction_currency_iso_code"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_transactions_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_transactions_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["router_id"],
            ["routers.id"],
            name=op.f("fk_transactions_router_id_routers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        op.f("ix_transactions_customer_id"), "transactions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_package_id"), "transactions", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_payment_status"), "transactions", ["payment_status"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_paystack_reference"),
        "transactions",
        ["paystack_reference"],
        unique=True,
    )
    op.create_index(op.f("ix_transactions_router_id"), "transactions", ["router_id"], unique=False)
    op.create_table(
        "activations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.String(length=80), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=False),
        sa.Column("target_profile", sa.String(length=120), nullable=False),
        sa.Column("target_disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "processing",
                "provisioning",
                "retry_required",
                "reconciliation_required",
                "success",
                "manual_review",
                "superseded",
                name="activation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="not_started",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_activations_activation_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "char_length(target_profile) > 0",
            name=op.f("ck_activations_activation_target_profile_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_activations_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_activations_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["router_id"],
            ["routers.id"],
            name=op.f("fk_activations_router_id_routers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["activations.id"],
            name=op.f("fk_activations_superseded_by_id_activations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_activations_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activations")),
    )
    op.create_index(
        op.f("ix_activations_activation_id"), "activations", ["activation_id"], unique=True
    )
    op.create_index(
        op.f("ix_activations_customer_id"), "activations", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_activations_next_retry_at"), "activations", ["next_retry_at"], unique=False
    )
    op.create_index(op.f("ix_activations_package_id"), "activations", ["package_id"], unique=False)
    op.create_index(op.f("ix_activations_router_id"), "activations", ["router_id"], unique=False)
    op.create_index(
        op.f("ix_activations_sequence_number"), "activations", ["sequence_number"], unique=True
    )
    op.create_index(op.f("ix_activations_status"), "activations", ["status"], unique=False)
    op.create_index(
        op.f("ix_activations_superseded_by_id"), "activations", ["superseded_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_activations_transaction_id"), "activations", ["transaction_id"], unique=True
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column("paystack_reference", sa.String(length=120), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processed",
                "ignored",
                "failed",
                name="payment_event_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="received",
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_payment_events_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_events")),
    )
    op.create_index(
        op.f("ix_payment_events_event_key"), "payment_events", ["event_key"], unique=True
    )
    op.create_index(
        op.f("ix_payment_events_event_type"), "payment_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_payment_events_paystack_reference"),
        "payment_events",
        ["paystack_reference"],
        unique=False,
    )
    op.create_index(op.f("ix_payment_events_status"), "payment_events", ["status"], unique=False)
    op.create_index(
        op.f("ix_payment_events_transaction_id"), "payment_events", ["transaction_id"], unique=False
    )
    op.create_table(
        "activation_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "payment_verification",
                "paystack_webhook",
                "customer_retry",
                "scheduled_reconciliation",
                "admin_retry",
                name="activation_trigger",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "processing",
                "success",
                "retry_required",
                "reconciliation_required",
                "manual_review",
                "superseded",
                name="activation_attempt_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="processing",
            nullable=False,
        ),
        sa.Column("observed_activation_id", sa.String(length=80), nullable=True),
        sa.Column("observed_profile", sa.String(length=120), nullable=True),
        sa.Column("observed_disabled", sa.Boolean(), nullable=True),
        sa.Column("router_state_before", sa.JSON(), nullable=True),
        sa.Column("router_state_after", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["activation_id"],
            ["activations.id"],
            name=op.f("fk_activation_attempts_activation_id_activations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activation_attempts")),
        sa.UniqueConstraint("activation_id", "attempt_number", name="uq_activation_attempt_number"),
    )
    op.create_index(
        op.f("ix_activation_attempts_activation_id"),
        "activation_attempts",
        ["activation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activation_attempts_outcome"), "activation_attempts", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_activation_attempts_trigger"), "activation_attempts", ["trigger"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("activation_id", sa.Uuid(), nullable=False),
        sa.Column("router_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "expired",
                "cancelled",
                "superseded",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR starts_at IS NULL OR expires_at > starts_at",
            name=op.f("ck_subscriptions_subscription_expiry_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["activation_id"],
            ["activations.id"],
            name=op.f("fk_subscriptions_activation_id_activations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_subscriptions_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_subscriptions_package_id_packages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["router_id"],
            ["routers.id"],
            name=op.f("fk_subscriptions_router_id_routers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscriptions_superseded_by_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_subscriptions_transaction_id_transactions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(
        op.f("ix_subscriptions_activation_id"), "subscriptions", ["activation_id"], unique=True
    )
    op.create_index(
        op.f("ix_subscriptions_customer_id"), "subscriptions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_package_id"), "subscriptions", ["package_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_router_id"), "subscriptions", ["router_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_superseded_by_id"),
        "subscriptions",
        ["superseded_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_transaction_id"), "subscriptions", ["transaction_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_transaction_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_superseded_by_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_router_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_package_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_customer_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_activation_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_activation_attempts_trigger"), table_name="activation_attempts")
    op.drop_index(op.f("ix_activation_attempts_outcome"), table_name="activation_attempts")
    op.drop_index(op.f("ix_activation_attempts_activation_id"), table_name="activation_attempts")
    op.drop_table("activation_attempts")
    op.drop_index(op.f("ix_payment_events_transaction_id"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_status"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_paystack_reference"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_event_type"), table_name="payment_events")
    op.drop_index(op.f("ix_payment_events_event_key"), table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_index(op.f("ix_activations_transaction_id"), table_name="activations")
    op.drop_index(op.f("ix_activations_superseded_by_id"), table_name="activations")
    op.drop_index(op.f("ix_activations_status"), table_name="activations")
    op.drop_index(op.f("ix_activations_sequence_number"), table_name="activations")
    op.drop_index(op.f("ix_activations_router_id"), table_name="activations")
    op.drop_index(op.f("ix_activations_package_id"), table_name="activations")
    op.drop_index(op.f("ix_activations_next_retry_at"), table_name="activations")
    op.drop_index(op.f("ix_activations_customer_id"), table_name="activations")
    op.drop_index(op.f("ix_activations_activation_id"), table_name="activations")
    op.drop_table("activations")
    op.drop_index(op.f("ix_transactions_router_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_paystack_reference"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payment_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_package_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_customer_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_email_otp_challenges_purpose"), table_name="email_otp_challenges")
    op.drop_index(op.f("ix_email_otp_challenges_expires_at"), table_name="email_otp_challenges")
    op.drop_index(op.f("ix_email_otp_challenges_email"), table_name="email_otp_challenges")
    op.drop_index(op.f("ix_email_otp_challenges_customer_id"), table_name="email_otp_challenges")
    op.drop_index(op.f("ix_email_otp_challenges_created_at"), table_name="email_otp_challenges")
    op.drop_table("email_otp_challenges")
    op.drop_index(op.f("ix_customer_sessions_token_hash"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_expires_at"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_customer_id"), table_name="customer_sessions")
    op.drop_table("customer_sessions")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_customer_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_admin_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_router_package_profiles_router_id"), table_name="router_package_profiles"
    )
    op.drop_index(
        op.f("ix_router_package_profiles_package_id"), table_name="router_package_profiles"
    )
    op.drop_table("router_package_profiles")
    op.drop_index(op.f("ix_customers_username"), table_name="customers")
    op.drop_index(op.f("ix_customers_router_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_index(op.f("ix_customers_account_status"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_admin_sessions_token_hash"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_expires_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_user_id"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index(op.f("ix_routers_status"), table_name="routers")
    op.drop_table("routers")
    op.drop_index(op.f("ix_packages_code"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_admin_users_role"), table_name="admin_users")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
